name: Build and deploy
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.REGISTRY_TOKEN }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t registry.digitalocean.com/scarey/web:main .
    - name: Push the Docker image
      run: docker push registry.digitalocean.com/scarey/web:main
    - name: Notify Watchtower
      env:
        WATCHTOWER_HTTP_TOKEN: ${{ secrets.WATCHTOWER_HTTP_TOKEN }}
      run: "curl -H 'Authorization: Bearer ${WATCHTOWER_HTTP_TOKEN}' scarey.me:8080/v1/update"
